FROM node:latest
# REACT_APP_BASE_URL -> Your deployment URL
# ENV REACT_APP_BASE_URL=https://komication.heroku.com



WORKDIR /app/backend

COPY ..
RUN npm install

EXPOSE 3000

ENTRYPOINT ["npm", "start"]
