FROM node:16
# REACT_APP_BASE_URL -> Your deployment URL
ENV REACT_APP_BASE_URL=https://ninatrill-esthetics.herokuapp.com/



WORKDIR /app
COPY package*.json ./

RUN npm install

COPY . .


RUN npm run build
# EXPOSE 5000

CMD ["npm", "install"]
